# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWRiNDJmNGYxYTFjNDllNzhkNDUyNGI0OGVkODZjN2Q3NzI2OWFmZGI0NmJhMTZlZDk3MzcyNjlmZDA1OGQwZGRiNTBlNjQ4ZDc4MDhlMWE4OGNjYWE4YTNiY2Q5NWY0OTNjYzAyZGYwMjNlM2ZjNGJiZTFjMDFlYzRjMjg0Y2I=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
